import mysql.connector
from tkinter import messagebox
from tkinter import ttk
from PIL import Image, ImageTk
import tkinter
import tkinter as tk
from tkinter import *
from tkinter import scrolledtext
def AccountOpening():
    def exitfun():
        window1.destroy()
    def save():
      a=t1.get()
      b=t2.get()
      c=t3.get()
      d=t4.get()
      e=t5.get("1.0",tkinter.END)
      f=t6.get()
      g=t7.get()
      h=t8.get()
      i=t9.get()
      j=cb1.get()+cb2.get()+cb3.get()
      k=t11.get()
      l=t12.get()
      if(a==""):
        messagebox.showinfo("status","Enter Account Number")
      elif(b==""):
        messagebox.showinfo('Status',"Enter Customer Name")
        window1.destroy()
        AccountOpening()
      elif(c==""):
        messagebox.showinfo('Status',"Enter Father name")
        window1.destroy()
        AccountOpening()
      elif(d==""):
        messagebox.showinfo('Status',"Enter Mother name")
        window1.destroy()
        AccountOpening()
      #elif(e==""):
        #messagebox.showwarning('Status',"Enter Address")
      elif(f==""):
        messagebox.showinfo('Status',"Enter Phone Number")
        window1.destroy()
        AccountOpening()
      elif(g==""):
        messagebox.showinfo('Status',"Enter Age")
        window1.destroy()
        AccountOpening()
      elif(h==""):
        messagebox.showinfo('Status',"Enter Amount")
        window1.destroy()
        AccountOpening()
      elif(i==""):
        messagebox.showinfo('Status',"Enter Nominee")
        window1.destroy()
        AccountOpening()
      elif(k==""):
        messagebox.showinfo('Status',"Enter Verified by")
        window1.destroy()
        AccountOpening()
      elif(l==""):
        messagebox.showinfo('Status',"Enter Security number")
        window1.destroy()
        AccountOpening()
      else:
        mydb = mysql.connector.connect(host="localhost",user="root",passwd="",database="bankingdb")
        mycursor= mydb.cursor()
        sql="INSERT INTO accountopening VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        val=(a,b,c,d,e,f,g,h,i,k,l,j)
        mycursor.execute(sql,val)
        sql="INSERT INTO balance VALUES (%s,%s)"
        val=(a,h)
        mycursor.execute(sql,val)
        mydb.commit()
        messagebox.showinfo("Record Saved Successfully")
        window1.destroy()
        AccountOpening()
        t1.delete(0,END)
        t2.delete(0,END)
        t3.delete(0,END)
        t4.delete(0,END)
        t5.delete(0,END)
        t6.delete(0,END)
        t7.delete(0,END)
        t8.delete(0,END)
        t9.delete(0,END)
        cb1.delete(0,END)
        cb2.delete(0,END)
        cb3.delete(0,END)
        t11.delete(0,END)
        t12.delete(0,END)
        t1.focus()
    window1=tkinter.Tk()
    window1.geometry("900x800+200+0")
    window1.title("Account Opening")
    frame=tk.Frame(window1)
    frame.pack(fill='both',expand='yes')
    #frame=tk.Frame(window,bg='grey')
    #frame.pack(fill='both',expand='yes')
    #render = ImageTk.PhotoImage(load)
    #img = tk.Label(frame,image=render)
    #img.image = render
    #img.place(x=0, y=50)
    heading=tk.Label(frame,text="Account Opening Form", font=("Times New Roman", 22),fg='blue')
    heading.place(x=340, y=30)
    an=tk.Label(frame,text='Account Number', font=("Times New Roman", 14))
    an.place(x=250,y=100)
    t1=tk.Entry(frame,text="",width=25)
    t1.place(x=430,y=100)
    cn=tk.Label(frame,text="Customer Name",bg='grey',font=("Times New Roman", 14),fg='blue')
    cn.place(x=250,y=150)
    t2=tk.Entry(frame,text="",width=25)
    t2.place(x=430,y=150)
    fn=tk.Label(frame,text="Father Name",bg='grey',font=("Times New Roman", 14),fg='blue')
    fn.place(x=250,y=200)
    t3=tk.Entry(frame,text="",width=25)
    t3.place(x=430,y=200)
    mn=tk.Label(frame,text="Mother Name",bg='grey',font=("Times New Roman", 14),fg='blue')
    mn.place(x=250,y=250)
    t4=tk.Entry(frame,text="",width=25)
    t4.place(x=430,y=250)
    address=tk.Label(frame,text="Address",bg='grey',font=("Times New Roman", 14),fg='blue')
    address.place(x=250,y=300)
    #t5=tk.Entry(frame,text="",width=25)
    #t5.place(x=430,y=300)
    t5=scrolledtext.ScrolledText(frame,width=15,height=5)
    t5.place(x=430,y=300)
    pn=tk.Label(frame,text="Phone number",bg='grey',font=("Times New Roman", 14),fg='blue')
    pn.place(x=250,y=400)
    t6=tk.Entry(frame,text="",width=25)
    t6.place(x=430,y=400)
    ag=tk.Label(frame,text="Age",bg='grey',font=("Times New Roman", 14),fg='blue')
    ag.place(x=250,y=450)
    t7=tk.Entry(frame,text="",width=25)
    t7.place(x=430,y=450)
    at=tk.Label(frame,text="Amount",bg='grey',font=("Times New Roman", 14),fg='blue')
    at.place(x=250,y=500)
    t8=tk.Entry(frame,text="",width=25)
    t8.place(x=430,y=500)
    nn=tk.Label(frame,text="Nominee",bg='grey',font=("Times New Roman", 14),fg='blue')
    nn.place(x=250,y=550)
    t9=tk.Entry(frame,text="",width=25)
    t9.place(x=430,y=550)
    od=tk.Label(frame,text="Opening Date",bg='grey',font=("Times New Roman", 14),fg='blue')
    od.place(x=250,y=600)
    cb1 = ttk.Combobox(frame,values=("Date","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"))
    cb1.place(x=430, y=600,width=60)
    cb1.current(0)
    #for cb1 in range(1,32):
    cb2 = ttk.Combobox(frame, values=("Month","January","Feburary","March","April","May","June","July","August","September","October","November","December"))
    cb2.place(x=500, y=600,width=60)
    cb2.current(0)
    cb3 = ttk.Combobox(frame, values=("Year",'2019','2020','2021','2022'))
    cb3.place(x=570, y=600,width=60)
    cb3.current(0)
    #t10=tk.Entry(frame,text="",width=25)
    #t10.place(x=430,y=600)
    vb=tk.Label(frame,text="Verified By",bg='grey',font=("Times New Roman", 14),fg='blue')
    vb.place(x=250,y=650)
    t11=tk.Entry(frame,text="",width=25)
    t11.place(x=430,y=650)
    sn=tk.Label(frame,text="Security Number",bg='grey',font=("Times New Roman", 14),fg='blue')
    sn.place(x=250,y=700)
    t12=tk.Entry(frame,text="",width=25)
    t12.place(x=430,y=700)
    bt=tk.Button(frame, text="Save",width='6',fg='blue',font=('Times New Roman',12),command=save)
    bt.place(x=700,y=650)
    bt1=tk.Button(frame, text="Exit",width='6',fg='blue',font=('Times New Roman',12),command=exitfun)
    bt1.place(x=780,y=650)
    window1.mainloop()
