import mysql.connector
from tkinter import messagebox
from tkinter import ttk
import tkinter
import tkinter as tk
from tkinter import *
from tkinter import scrolledtext
def AccountClosing():
    def exitfun():
        window.destroy()
    def display(event):
      aa=cb.get()
      t1.delete(0,END)
      t2.delete(0,END)
      t3.delete(0,END)
      t4.delete(0,END)
      t5.delete(1.0,END)
      t6.delete(0,END)
      t7.delete(0,END)
      t8.delete(0,END)
      t9.delete(0,END)
      t10.delete(0,END)
      mydb = mysql.connector.connect(host="localhost",user="root",passwd="",database="bankingdb")
      mycursor= mydb.cursor()
      sql="SELECT * FROM accountopening where accountnumber=(%s)"
      val=(aa,)
      mycursor.execute(sql,val)
      myresult=mycursor.fetchall()
      for x in myresult:
        t1.insert(INSERT,x[0])
        t2.insert(INSERT,x[1])
        t3.insert(INSERT,x[2])
        t4.insert(INSERT,x[3])
        t5.insert(INSERT,x[4])
        #t5["text"]=x[5]
        t6.insert(INSERT,x[5])
        t7.insert(INSERT,x[6])
        t9.insert(INSERT,x[8])
        t10.insert(INSERT,x[9])
      sql="SELECT * FROM balance where accountnumber=(%s)"
      val=(aa,)
      mycursor.execute(sql,val)
      myresult=mycursor.fetchall()
      for x1 in myresult:
        t8.insert(INSERT,x1[1])
    window=tkinter.Tk()
    window.geometry("1700x800+0+0")
    window.title("Account Closing")
    frame=tk.Frame(window,bg='grey')
    frame.pack(fill='both',expand='yes')
    heading=tk.Label(frame,text="Closing Balance", bg='grey', font=("Times New Roman", 20),fg='black')
    heading.place(x=340, y=30)
    sa=tk.Label(frame,text='Select Account Number',bg='grey',fg='blue',font=("Times New Roman", 14))
    sa.place(x=180,y=100)
    cb = ttk.Combobox(frame, values=("Select"))
    cb.place(x=400, y=100)
    cb.current(0)
    an=tk.Label(frame,text='Account Number',bg='grey',fg='white',font=("Times New Roman", 14))
    an.place(x=950,y=100)
    t1=tk.Entry(frame,text="",width=25)
    t1.place(x=1100,y=100)
    cn=tk.Label(frame,text="Customer Name",bg='grey',fg='white',font=("Times New Roman", 14))
    cn.place(x=950,y=150)
    t2=tk.Entry(frame,text="",width=25)
    t2.place(x=1100,y=150)
    fn=tk.Label(frame,text="Father Name",bg='grey',fg='white',font=("Times New Roman", 14))
    fn.place(x=950,y=200)
    t3=tk.Entry(frame,text="",width=25)
    t3.place(x=1100,y=200)
    mn=tk.Label(frame,text="Mother Name",bg='grey',fg='white',font=("Times New Roman", 14))
    mn.place(x=950,y=250)
    t4=tk.Entry(frame,text="",width=25)
    t4.place(x=1100,y=250)
    address=tk.Label(frame,text="Address",bg='grey',fg='white',font=("Times New Roman", 14))
    address.place(x=950,y=300)
    #t5=tk.Entry(frame,text="",width=25)
    #t5.place(x=1200,y=300)
    t5=scrolledtext.ScrolledText(frame,width=10,height=5)
    t5.place(x=1100,y=300)
    pn=tk.Label(frame,text="Phone number",bg='grey',fg='white',font=("Times New Roman", 14))
    pn.place(x=950,y=400)
    t6=tk.Entry(frame,text="",width=25)
    t6.place(x=1100,y=400)
    ag=tk.Label(frame,text="Age",bg='grey',fg='white',font=("Times New Roman", 14))
    ag.place(x=950,y=450)
    t7=tk.Entry(frame,text="",width=25)
    t7.place(x=1100,y=450)
    at=tk.Label(frame,text="Amount",bg='grey',fg='white',font=("Times New Roman", 14))
    at.place(x=950,y=500)
    t8=tk.Entry(frame,text="",width=25)
    t8.place(x=1100,y=500)
    nn=tk.Label(frame,text="Nominee",bg='grey',fg='white',font=("Times New Roman", 14))
    nn.place(x=950,y=550)
    t9=tk.Entry(frame,text="",width=25)
    t9.place(x=1100,y=550)
    od=tk.Label(frame,text="Opening Date",bg='grey',fg='white',font=("Times New Roman", 14))
    od.place(x=950,y=600)
    t10=tk.Entry(frame,text="",width=25)
    t10.place(x=1100,y=600)
    bt=tk.Button(frame, text="Display",width='6',fg='blue',font=('Times New Roman',12))
    bt.place(x=580,y=100)
    bt.bind("<Button>",display)
    bt1=tk.Button(frame, text="Exit",width='6',fg='red',font=('Times New Roman',12),command=exitfun)
    bt1.place(x=1150,y=660)
    mydb = mysql.connector.connect(
       host="localhost",
       user="root",
       passwd="",
       database="bankingdb"
       )
    mycursor = mydb.cursor()
    mycursor.execute("SELECT * FROM accountopening")
    myresult = mycursor.fetchall()
    for x in myresult:
      cb['values']+=(x[0],)
    window.mainloop()
